[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/models/*"
  to = "https://essentia.upf.edu/models/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
